import string
print(string.__all__)
print(string.ascii_letters)
print(string.ascii_uppercase)
print(string.ascii_lowercase)
print(string.digits)
print(string.octdigits)
print(string.hexdigits)
print(string.printable)
print(len(string.printable))
print(len(string.punctuation))
print(string.whitespace)
print(len(string.whitespace))